# Entra ID authentication in front of the dashboard.
#
# These resources live in this module rather than beside the other Entra ID
# identities because of an ordering constraint that cannot be worked around:
# the app registration needs the dashboard's host name, which is derived from
# the environment created here, and the Container App needs the client secret
# to exist before it starts. Splitting them across modules makes Terraform see a
# cycle even though no individual resource depends on itself.

locals {
  # The host name is derived rather than read back from the Container App, so
  # the app registration can exist before the app does. A redirect URI that only
  # appears after the app is running would leave the page reachable and
  # unauthenticated in between.
  dashboard_fqdn         = "ca-${var.name_prefix}-dashboard.${azurerm_container_app_environment.this.default_domain}"
  dashboard_redirect_uri = "https://${local.dashboard_fqdn}/.auth/login/aad/callback"
  client_secret_name     = "dashboard-client-secret"
}

resource "azuread_application" "dashboard" {
  count = var.dashboard_enabled ? 1 : 0

  display_name     = "${var.name_prefix}-dashboard"
  owners           = [var.deployer_object_id]
  sign_in_audience = "AzureADMyOrg"
  description      = "Sign-in for the trading bot dashboard. Single tenant."

  web {
    redirect_uris = [local.dashboard_redirect_uri]

    implicit_grant {
      # The authorization code flow is used, so neither implicit grant is
      # needed. Leaving them on is how an application ends up handing tokens to
      # a browser that was never meant to hold one.
      access_token_issuance_enabled = false
      id_token_issuance_enabled     = false
    }
  }

  required_resource_access {
    # Microsoft Graph
    resource_app_id = "00000003-0000-0000-c000-000000000000"

    resource_access {
      # User.Read, delegated. The dashboard needs to know that a sign-in
      # happened and nothing else; it reads no profile data and calls no API.
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d"
      type = "Scope"
    }
  }
}

resource "azuread_service_principal" "dashboard" {
  count = var.dashboard_enabled ? 1 : 0

  client_id = azuread_application.dashboard[0].client_id
  owners    = [var.deployer_object_id]
}

# Easy Auth uses the authorization code flow, which requires a confidential
# client, which requires a secret. There is no secretless variant for this flow.
# The secret is generated by Terraform and stored in Key Vault, the same
# treatment the database password gets, so it is never typed by a person and
# never appears in the repository or in CI.
resource "azuread_application_password" "dashboard" {
  count = var.dashboard_enabled ? 1 : 0

  application_id = azuread_application.dashboard[0].id
  display_name   = "container-apps-easy-auth"
  end_date       = var.client_secret_end_date
}

resource "azurerm_key_vault_secret" "dashboard_client_secret" {
  count = var.dashboard_enabled ? 1 : 0

  name         = local.client_secret_name
  value        = azuread_application_password.dashboard[0].value
  key_vault_id = var.key_vault_id
  content_type = "text/plain"
  tags         = var.tags

  # checkov:skip=CKV_AZURE_41:The expiry that matters is on the Entra ID credential itself, set by client_secret_end_date. A second expiry on the vault copy would take the dashboard down while the credential it mirrors is still valid.
}

# Authentication is enforced by the platform, in front of the container. The
# application therefore contains no authentication code at all, which is the
# point: there is no code path that can be made to skip the check.
resource "azapi_resource" "dashboard_auth" {
  count = var.dashboard_enabled ? 1 : 0

  type      = "Microsoft.App/containerApps/authConfigs@2024-03-01"
  name      = "current"
  parent_id = azurerm_container_app.dashboard[0].id

  body = {
    properties = {
      platform = {
        enabled = true
      }

      globalValidation = {
        # Redirect rather than return 401: the page is opened by a person in a
        # browser, and an unauthenticated API response is not a sign-in prompt.
        unauthenticatedClientAction = "RedirectToLoginPage"
        redirectToProvider          = "azureactivedirectory"

        # The probes have to answer before a replica is considered healthy, and
        # the platform does not sign in to call them.
        excludedPaths = ["/healthz", "/readyz"]
      }

      identityProviders = {
        azureActiveDirectory = {
          enabled = true

          registration = {
            clientId                = azuread_application.dashboard[0].client_id
            clientSecretSettingName = local.client_secret_name
            openIdIssuer            = "https://sts.windows.net/${var.tenant_id}/v2.0"
          }

          validation = {
            # Without an explicit audience the platform accepts any token this
            # tenant issued, including one minted for a different application.
            allowedAudiences = ["api://${azuread_application.dashboard[0].client_id}"]

            defaultAuthorizationPolicy = {
              allowedPrincipals = {
                identities = var.dashboard_allowed_principal_ids
              }
            }
          }
        }
      }

      login = {
        tokenStore = {
          # Off deliberately. A token store needs a storage account and a SAS
          # URL, which is a credential to rotate, and Azure rejects the config
          # outright without one. The dashboard calls no downstream API: it only
          # needs to know a sign-in happened, so it holds no token worth storing.
          enabled = false
        }
      }
    }
  }

  # Replacing the app replaces its auth config, and applying them in the wrong
  # order would leave a window where the page answers without a sign-in.
  depends_on = [azurerm_key_vault_secret.dashboard_client_secret]
}
