# Entra ID authentication in front of the dashboard.
#
# These resources live in this module rather than beside the other Entra ID
# identities because of an ordering constraint that cannot be worked around:
# the app registration needs the dashboard's host name, which is derived from
# the environment created here, and the Container App needs the client secret
# to exist before it starts. Splitting them across modules makes Terraform see a
# cycle even though no individual resource depends on itself.

locals {
  # The host name is derived rather than read back from the Container App, so
  # the app registration can exist before the app does. A redirect URI that only
  # appears after the app is running would leave the page reachable and
  # unauthenticated in between.
  dashboard_fqdn         = "ca-${var.name_prefix}-dashboard.${azurerm_container_app_environment.this.default_domain}"
  dashboard_redirect_uri = "https://${local.dashboard_fqdn}/.auth/login/aad/callback"
  client_secret_name     = "dashboard-client-secret"
}

resource "azuread_application" "dashboard" {
  count = var.dashboard_enabled ? 1 : 0

  display_name     = "${var.name_prefix}-dashboard"
  owners           = [var.deployer_object_id]
  sign_in_audience = "AzureADMyOrg"
  description      = "Sign-in for the trading bot dashboard. Single tenant."

  web {
    redirect_uris = [local.dashboard_redirect_uri]

    implicit_grant {
      # Access token issuance stays off: the dashboard calls no API, so an
      # access token in a browser would be a credential with nothing to open.
      access_token_issuance_enabled = false

      # ID token issuance has to be on. Easy Auth asks Entra ID for
      # `response_type=code+id_token`, the hybrid flow, and without this the
      # authorize request is rejected. This was found by reading the redirect
      # the platform actually issues rather than by assuming the plain code flow.
      id_token_issuance_enabled = true
    }
  }

  required_resource_access {
    # Microsoft Graph
    resource_app_id = "00000003-0000-0000-c000-000000000000"

    resource_access {
      # User.Read, delegated. The dashboard needs to know that a sign-in
      # happened and nothing else; it reads no profile data and calls no API.
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d"
      type = "Scope"
    }
  }
}

resource "azuread_service_principal" "dashboard" {
  count = var.dashboard_enabled ? 1 : 0

  client_id = azuread_application.dashboard[0].client_id
  owners    = [var.deployer_object_id]
}

# Easy Auth uses the authorization code flow, which requires a confidential
# client, which requires a secret. There is no secretless variant for this flow.
# The secret is generated by Terraform and stored in Key Vault, the same
# treatment the database password gets, so it is never typed by a person and
# never appears in the repository or in CI.
resource "azuread_application_password" "dashboard" {
  count = var.dashboard_enabled ? 1 : 0

  application_id = azuread_application.dashboard[0].id
  display_name   = "container-apps-easy-auth"
  end_date       = var.client_secret_end_date
}

resource "azurerm_key_vault_secret" "dashboard_client_secret" {
  count = var.dashboard_enabled ? 1 : 0

  name         = local.client_secret_name
  value        = azuread_application_password.dashboard[0].value
  key_vault_id = var.key_vault_id
  content_type = "text/plain"
  tags         = var.tags

  # checkov:skip=CKV_AZURE_41:The expiry that matters is on the Entra ID credential itself, set by client_secret_end_date. A second expiry on the vault copy would take the dashboard down while the credential it mirrors is still valid.
}

# Authentication is enforced by the platform, in front of the container. The
# application therefore contains no authentication code at all, which is the
# point: there is no code path that can be made to skip the check.
resource "azapi_resource" "dashboard_auth" {
  count = var.dashboard_enabled ? 1 : 0

  # The identity-based token store needs a recent API version; older ones only
  # accept a shared access signature.
  type      = "Microsoft.App/containerApps/authConfigs@2025-01-01"
  name      = "current"
  parent_id = azurerm_container_app.dashboard[0].id

  # The provider's bundled schema still requires a shared access signature for
  # the token store. The service accepts an identity instead, so the local
  # check is turned off and the API is left to validate the payload.
  schema_validation_enabled = false

  body = {
    properties = {
      platform = {
        enabled = true
      }

      globalValidation = {
        # Redirect rather than return 401: the page is opened by a person in a
        # browser, and an unauthenticated API response is not a sign-in prompt.
        unauthenticatedClientAction = "RedirectToLoginPage"
        redirectToProvider          = "azureactivedirectory"

        # The probes have to answer before a replica is considered healthy, and
        # the platform does not sign in to call them.
        excludedPaths = ["/healthz", "/readyz"]
      }

      identityProviders = {
        azureActiveDirectory = {
          enabled = true

          registration = {
            clientId                = azuread_application.dashboard[0].client_id
            clientSecretSettingName = local.client_secret_name
            openIdIssuer            = "https://sts.windows.net/${var.tenant_id}/v2.0"
          }

          # An authorisation policy is sent only when there is something to put
          # in it. An empty allowed-principals list is not "everyone": it is an
          # allow-list naming nobody, and the platform answers 401 rather than
          # offering a sign-in that could never succeed.
          validation = merge(
            {
              # Without an explicit audience the platform accepts any token this
              # tenant issued, including one minted for a different application.
              allowedAudiences = ["api://${azuread_application.dashboard[0].client_id}"]
            },
            length(var.dashboard_allowed_principal_ids) > 0 ? {
              defaultAuthorizationPolicy = {
                allowedPrincipals = {
                  identities = var.dashboard_allowed_principal_ids
                }
              }
            } : {},
          )
        }
      }

      login = {
        # Required for the browser flow. Measured rather than assumed: with the
        # token store off, the app stored RedirectToLoginPage and still answered
        # 401 with a bearer challenge, which protects the page and makes it
        # unusable in a browser.
        tokenStore = {
          enabled = true

          azureBlobStorage = {
            # Addressed by URI with a managed identity, so no storage key and no
            # shared access signature exists to rotate or leak.
            blobContainerUri          = "https://${azurerm_storage_account.token_store[0].name}.blob.core.windows.net/${azurerm_storage_container.token_store[0].name}"
            managedIdentityResourceId = var.user_assigned_identity_id
          }
        }
      }
    }
  }

  # Replacing the app replaces its auth config, and applying them in the wrong
  # order would leave a window where the page answers without a sign-in.
  depends_on = [azurerm_key_vault_secret.dashboard_client_secret]
}
