variable "name" {
  description = "Flexible Server name. Globally unique, lowercase."
  type        = string
}

variable "resource_group_name" {
  description = "Resource group that holds the server."
  type        = string
}

variable "location" {
  description = "Azure region."
  type        = string
}

variable "postgres_version" {
  description = "Major PostgreSQL version."
  type        = string
  default     = "16"
}

variable "delegated_subnet_id" {
  description = "Subnet delegated to Microsoft.DBforPostgreSQL/flexibleServers."
  type        = string
}

variable "private_dns_zone_id" {
  description = "Private DNS zone resolving the server FQDN inside the VNet."
  type        = string
}

variable "administrator_login" {
  description = "Administrator user name."
  type        = string
  default     = "tradingadmin"
}

variable "administrator_password" {
  description = "Administrator password, generated by the caller and stored in Key Vault."
  type        = string
  sensitive   = true
}

variable "sku_name" {
  description = "Compute SKU. B_Standard_B1ms is the cheapest that runs this workload."
  type        = string
  default     = "B_Standard_B1ms"
}

variable "storage_mb" {
  description = "Storage size. 32768 is the smallest allowed."
  type        = number
  default     = 32768
}

variable "backup_retention_days" {
  description = "Backup retention. 7 days is the minimum and is free."
  type        = number
  default     = 7
}

variable "availability_zone" {
  description = "Availability zone, pinned to avoid a permanent plan diff."
  type        = string
  default     = "1"
}

variable "database_name" {
  description = "Application database created on the server."
  type        = string
  default     = "trading"
}

variable "log_analytics_workspace_id" {
  description = "Workspace receiving the PostgreSQL logs."
  type        = string
}

variable "tags" {
  description = "Tags applied to every resource."
  type        = map(string)
}
