"""create trading tables

Revision ID: 2fb880750d65
Revises:
Create Date: 2026-09-15 10:32:42.592305+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2fb880750d65"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("cash_quote", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("position_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("equity_quote", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("day_opening_equity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_equity_snapshots_cycle_id"), "equity_snapshots", ["cycle_id"], unique=False
    )
    op.create_index(
        "ix_equity_snapshots_symbol_taken_at",
        "equity_snapshots",
        ["symbol", "taken_at"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("venue_order_id", sa.String(length=64), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_order_id"),
    )
    op.create_index(op.f("ix_orders_cycle_id"), "orders", ["cycle_id"], unique=False)
    op.create_table(
        "positions",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("strength", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_cycle_id"), "signals", ["cycle_id"], unique=False)
    op.create_index("ix_signals_symbol_as_of", "signals", ["symbol", "as_of"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fee_quote", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fills_client_order_id"), "fills", ["client_order_id"], unique=False)
    op.create_index(op.f("ix_fills_order_id"), "fills", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fills_order_id"), table_name="fills")
    op.drop_index(op.f("ix_fills_client_order_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index("ix_signals_symbol_as_of", table_name="signals")
    op.drop_index(op.f("ix_signals_cycle_id"), table_name="signals")
    op.drop_table("signals")
    op.drop_table("positions")
    op.drop_index(op.f("ix_orders_cycle_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_equity_snapshots_symbol_taken_at", table_name="equity_snapshots")
    op.drop_index(op.f("ix_equity_snapshots_cycle_id"), table_name="equity_snapshots")
    op.drop_table("equity_snapshots")
    # ### end Alembic commands ###
